// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VariacaoAtivos.Infra.Data.Contexts;

#nullable disable

namespace VariacaoAtivos.Infra.Data.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("VariacaoAtivos.Domain.Entity.VariacaoAtivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ativo")
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ATIVO");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA");

                    b.Property<int>("Dia")
                        .HasColumnType("int")
                        .HasColumnName("DIA");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("VALOR");

                    b.Property<decimal?>("VariacaoDia")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("VARIACAODIA");

                    b.Property<decimal?>("VariacaoPrimeiraData")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("VARIACAOPRIMEIRADATA");

                    b.HasKey("Id");

                    b.ToTable("VARIACAOATIVO", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
