version: '3.4'

services:
  variacaoativoswebapi:
    image: image_variacao_ativos
    build:
      context: .
      dockerfile: VariacaoAtivos.WebApi/Dockerfile
    ports:
      - 5279:5279
    depends_on:
     - sqldata

  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "SuperPassword@23"
      ACCEPT_EULA: "Y"
    ports: 
      - "1433:1433"